version: "3.8"
services:
  apim:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace
    depends_on:
      - mysql

  mysql:
    image: mysql:8
    ports:
      - "3316:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: wso2carbon
      MYSQL_PASSWORD: wso2carbon
    volumes:
      - ../conf/mysql/scripts:/docker-entrypoint-initdb.d
      - ../conf/mysql/conf/my.cnf:/etc/mysql/mysql.conf.d/my.cnf
      - mysql-apim-data:/var/lib/mysql
    ulimits:
      nofile:
        soft: 20000
        hard: 40000
    healthcheck:
      test: ["CMD", "sh", "-c", "mysqladmin ping -uroot -proot && [ -f /var/lib/mysql/initialization-complete.flag ]"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s

volumes:
  mysql-apim-data:
