version: "3.8"
services:
  apim:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace
    depends_on:
      - mysql

  mysql:
    image: mysql:8
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: wso2carbon
      MYSQL_PASSWORD: wso2carbon
    ports:
      - "33060:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
